create table person
(
    id       integer generated by default as identity
        primary key,
    login    varchar(100),
    password varchar(100),
    role     varchar(255)
);

alter table person
    owner to postgres;

create table category
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

alter table category
    owner to postgres;

create table product
(
    id          integer generated by default as identity
        primary key,
    city        varchar(255),
    description varchar(2550),
    price       real not null,
    seller      varchar(255),
    title       varchar(255),
    warehouse   varchar(255),
    date_time   timestamp,
    category_id integer
        constraint fk1mtsbur82frn64de7balymq9s
            references category
);

alter table product
    owner to postgres;

create table image
(
    id         integer generated by default as identity
        primary key,
    file_name  varchar(255),
    product_id integer not null
        constraint fkgpextbyee3uk9u6o2381m7ft1
            references product
);

alter table image
    owner to postgres;

create table product_cart
(
    id         integer generated by default as identity
        primary key,
    person_id  integer
        constraint fksgnkc1ko2i1o9yr2p63ysq3rn
            references person,
    product_id integer
        constraint fkhpnrxdy3jhujameyod08ilvvw
            references product
);

alter table product_cart
    owner to postgres;

create table orders
(
    id         integer generated by default as identity
        primary key,
    count      integer not null,
    date_time  timestamp,
    number     varchar(255),
    price      real    not null,
    status     integer,
    person_id  integer not null
        constraint fk1b0m4muwx1t377w9if3w6wwqn
            references person,
    product_id integer not null
        constraint fk787ibr3guwp6xobrpbofnv7le
            references product
);

alter table orders
    owner to postgres;


